app/app/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from erp.login.views import ViewLogin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('erp.Dashboard_user.urls')),
    path('', include('erp.dashboard.urls')),
    path('', include('erp.userauths.urls')),

    path('login/', ViewLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/erp/userauths/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import AbstractUser

from app.settings import MEDIA_URL, STATIC_URL


def validate_dni_length(value):
    if len(str(value)) != 8:
        raise ValidationError(
            ('El DNI debe tener exactamente 8 dígitos.'),
            code='invalid_dni_length'
        )


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    DNI = models.PositiveIntegerField(blank=True, null=True, unique=True,validators=[validate_dni_length])
    image = models.ImageField(upload_to='users/', default='users/default.png', null=True, blank=True)
    nombres = models.CharField(max_length=200, null=True, blank=True)
    apellidos = models.CharField(max_length=200, null=True, blank=True)
    verified = models.BooleanField(default=False, null=True, blank=True)
    #Contribuyente attrs
    cod_contri_rentas = models.PositiveIntegerField(unique=True, null=True, blank=True, verbose_name='Codigo de rentas :')
    cod_predial_rentas = models.PositiveIntegerField(unique=True, null=True, blank=True)
    persona_juridica = models.BooleanField(default=False)
    ruc = models.PositiveIntegerField(blank=True, null=True)
    telefono = models.PositiveIntegerField(blank=True, null=True)
    Deudas = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.DNI)

    def contar_deudas_pendientes(self):
        # Contar las deudas pendientes asociadas a este contribuyente
        cantidad_deudas_pendientes = Deuda.objects.filter(contribuyente=self, estado='pendiente').count()
        return cantidad_deudas_pendientes




ESTADO_CHOICES = (
    ('pendiente', 'Pendiente'),
    ('cancelado', 'Cancelado'),
    ('vencido', 'vencido'),
)


class Predio(models.Model):
    cuc = models.CharField(max_length=50, unique=True)
    cod_ref_catastral = models.CharField(max_length=13)
    ubicacion = models.CharField(max_length=500)
    propietario = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)





    def __str__(self):
        return self.cuc

class Deuda(models.Model):
    contribuyente = models.ForeignKey(Profile, on_delete=models.CASCADE)
    deuda = models.BooleanField()
    monto_deuda = models.PositiveIntegerField()
    fecha = models.DateTimeField(auto_now_add=True)
    fecha_edit = models.DateTimeField(auto_now=True)
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='pendiente')  # Agregamos el campo de estado
    # Puedes agregar más campos relacionados con la deuda, como fecha, descripción, etc.

    def __str__(self):
        return f"Deuda de {self.contribuyente} - Monto: {self.monto_deuda}"

    def save(self, *args, **kwargs):
        # Verificar el estado antes de guardar la deuda
        if self.estado == 'pendiente':
            if not self.id:
                self.contribuyente.Deudas = self.contribuyente.contar_deudas_pendientes() + 1
        elif self.estado == 'cancelado':

            self.contribuyente.Deudas = self.contribuyente.contar_deudas_pendientes() - 1

        self.contribuyente.save()
        super().save(*args, **kwargs)


class Construccion(models.Model):
    predio = models.ForeignKey(Predio, on_delete=models.CASCADE)
    numero_piso = models.PositiveIntegerField()
    material_estructural_predominante = models.CharField(max_length=50)
    estado_conservacion = models.CharField(max_length=50)
    estado_construccion = models.CharField(max_length=50)

    def __str__(self):
        return f"Construcción en {self.predio} - Piso {self.numero_piso}"

app/templates/delete.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action="">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="alert alert-danger alert-dismissible">
                    <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                    ¿Estas seguro de eliminar el registro nro {{ object.id }}?
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Si, aceptar
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>

{% endblock %}

app/templates/footer.html
<footer class="main-footer text-center">
    <strong>Copyright &copy;2023  <a href="#">AnderDev</a>.</strong><br>
    Todos los derechos reservados.
</footer>

app/templates/form.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'lib/select2-4.0.13/select2-4.0.13/dist/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/select2-4.0.13/select2-4.0.13/select2-bootstrap4.min.css' %}">
    <script src="{% static 'lib/select2-4.0.13/select2-4.0.13/dist/js/select2.min.js' %}"></script>
{% endblock %}
{% load widget_tweaks %}
{% block content %}
    <form method="post"  enctype="multipart/form-data">
        <div class="card card-dark">
            <div class="card-header" style="background-color: #022F50 !important;">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i style="margin-right: 10px" class="fas fa-user-plus"></i>
                    {% else %}
                        <i style="margin-right: 10px" class="fas fa-user-edit"></i>
                    {% endif %}

                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d15608.771322963388!2d-77.0679477!3d-12.0302419!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses-419!2spe!4v1705607341464!5m2!1ses-419!2spe" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label>{{ field.label }}:</label>
                        {{ field }}
                    </div>
                    
                {% endfor %}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    {% block javascript %}
        <script>
        $(document).ready(function () {
                // Función para habilitar o deshabilitar el campo RUC
                function toggleRucField() {
                    var personaJuridica = $('#id_persona_juridica').prop('checked');
                    var rucInput = $('#id_ruc');

                    // Verificar si el checkbox de persona jurídica está marcado
                    if (personaJuridica) {
                        // Si está marcado, desactivar el campo RUC y borrar su valor
                        rucInput.prop('disabled', true);
                        rucInput.val('');
                    } else {
                        // Si no está marcado, habilitar el campo RUC
                        rucInput.prop('disabled', false);
                    }
                }

                // Llamar a la función al cargar la página
                toggleRucField();

                // Llamar a la función cuando cambie el valor de persona_juridica
                $('#id_persona_juridica').change(function () {
                    toggleRucField();
                });
            });

        errors = ''
         {% if form.errors %}
             {% for field in form %}
                 {% for error in field.errors %}
                     errors+='{{ error }}'
                 {% endfor %}
             {% endfor %}
             Swal.fire({
                 title : 'Error!',
                 text: errors,
                 icon: 'error',
                 confirmButtonText: 'Ok'
             })
         {% endif %}

        $('.select2').select2({
            theme : "bootstrap4"
        });

        </script>
    {% endblock %}
{% endblock %}

app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link  rel="icon"   href="{% static 'img/logo.jpg' %}" type="image/png" />
    <title>{{ title }}</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
    <!-- Sweetalert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/sweetalert2-9.10.0/sweetalert2.min.css' %}">
    <!-- Jquery Confirm -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- Functions -->
    <script src="{% static 'js/functions.js' %}"></script>


    <!-- Block head -->
    {% block head %}

    {% endblock %}
</head>
{% block body %}
    
{% endblock %}

</html>

app/templates/layout.html
{% extends 'vtc/body.html' %}

app/templates/list.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
    <link href="{% static 'lib/datatables-1.10.20/cdn.datatables.net_v_bs4_dt-1.13.6_datatables.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/datatables-1.10.20/cdn.datatables.net_v_dt_dt-1.13.6_datatables.min.js' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">



    {% block head_list %}

    {% endblock %}

{% endblock %}

{% block content %}
    <div class="card card-primary">
        <div class="card-header" style="background-color: #022F50 !important;">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                {{ title }}
            </h3>
        </div>
        <div class="card-body">
            <table class="table" id="data">
                <thead>
                {% block columns %}

                {% endblock %}
                </thead>
                <tbody>
                {% block rows %}

                {% endblock %}
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">
                <i class="fas fa-plus"></i> Nuevo registro
            </a>
            <a href="{{ list_url }}" class="btn btn-success btn-flat">
                <i class="fas fa-sync"></i> Actualizar
            </a>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">
    $(document).ready(function(){
        $('#data').DataTable( {
                responsive: true
        } );
    })

    </script>
{% endblock %}